#!/usr/bin/env python3
__doc__ = """Simple two-way Git-TFS bridge"""

import argparse
from core import *
import fetch, pull, push, wi

argParser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
parsers = argParser.add_subparsers(title='Commands:')
for m in [pull, fetch, push, wi]:
    commandType = getattr(m, m.__name__)
    cmd = commandType()
    ctorArgs = cmd.argParserCtorArgs()
    ctorArgs['help'] = ctorArgs['description']
    parser = parsers.add_parser(m.__name__, **ctorArgs)
    cmd.initArgParser(parser)

args = argParser.parse_args()
args.cmd.runWithArgs(args)