#!/usr/bin/env python3
import runpy
from core import *

def usage():
    print('Usage is not written yet. Sorry.')

def main():
    if len(sys.argv) <= 1:
        usage()
        return
    command = sys.argv.pop(1)
    if command.startswith('-'):
        usage()
        return

    sys.argv[0] += command
    try:
        return runpy.run_module(command, run_name='__main__')
    except ImportError:
        fail('Command %s not found' % command)

if __name__ == '__main__':
    GitTfException.run(main)