#!/bin/bash

echo Fetching from TFS
lastCommit=$( git log -1 --format=%H tfs )
lastChangeset=$( git notes show $lastCommit | grep -Po '^\d+' | tail -1 )
if [ -z "$lastChangeset" ]; then
  echo Last changeset could not determined. Probably the last commit is missing a tf note. Commit: $lastCommit
  exit 7
fi
echo Last synchronized changeset: $lastChangeset

latestCommit=$( $tf history -stopAfter:1 -recursive . | grep -oP '^\d+' )
echo Latest changeset on TFS: $latestCommit
if [ $lastChangeset -eq $latestCommit ]; then
  echo Nothing to fetch
  exit
fi

tfHistoryCmd="$tf history -recursive -version:C$lastChangeset~C$latestCommit ."
echo $tfHistoryCmd
tfHistory=$( $tfHistoryCmd | grep -P '^\d+\s{2,}\w+' | tac | tail -n +2 )
echo $( min $( echo "$tfHistory" | wc -l ) $number ) changeset\(s\) to fetch


echo Making files read-only
find -type f -exec chmod -w {} \;
expect0 chmod -R +w .git

while read -r line; do
  changeset=$( echo $line | grep -Po '^\d+' )
  if [ -z $changeset ]; then continue; fi

  echo
  echo Fetching \"$line\"...

  comment=$tmpDir/comment
  echo $line | grep -Po '(?<=\d:\d\d:\d\d [AP]M ).+$' > $comment
  if [ ! -s $comment ]; then
    if [ $( echo $line | grep -Pc '\d+:\d+:\d+ [AP]M ?$' ) -eq 0 ]; then
      echo "Could not parse comment!"
      echo $line
      echo Here is entire history:
      echo "$tfHistory"
      exit 1
    fi
    echo Comment is empty, so using the entire line as a commit comment
    echo "$line" > $comment
  fi

  expect0 $tf get -version:$changeset -recursive . | indent

  echo Committing to Git...
  author=$( echo $line | grep -Po '(?<=COMPONENTONE\\)[^\s]+' )
  expect0 git add -A .
  expect0 git commit -F $comment "--author=\"$author <$author@$domain>\"" | indent

  # adding a note
  echo "$line" > $tmpDir/note
  git notes add -F $tmpDir/note $( git log -1 --format=%H )

  decNumber
  if [ $number -eq 0 ]; then break; fi
done < <( echo "$tfHistory" )

echo Making files writable
find -type f -exec chmod +w {} \;
